#!/bin/bash
bundle_install() {
  cd $1 

  if [ "$TMUX" ]; then
    tmux new-window -d bundle install
  else
    bundle install
  fi
}

gem_ctags() {
  cd $1 

  if [ "$TMUX" ]; then
    tmux new-window -d gem ctags
  else
    gem ctags
  fi
}

find_gemfiles_and_run_tools() {
  find . -type f -name 'Gemfile' | sed -r 's|/[^/]+$||' |sort |uniq | while read line; do
    echo "Executing bundle install for $line"
    $(bundle_install $line) &

    echo "Executing gem ctags"
    $(gem_ctags $line) &
  done
}

find_gemfiles_and_run_tools
